// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"fmt"
	"gin-server/internal/config"
	"gin-server/internal/controller"
	"gin-server/internal/database"
	"gin-server/internal/repository"
	"gin-server/internal/repository/mongodb"
	"gin-server/internal/repository/mysql"
	"gin-server/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeContainer 使用Wire注入依赖
func InitializeContainer(cfg *config.Config) (*Container, error) {
	db, err := provideDB(cfg)
	if err != nil {
		return nil, err
	}
	userRepository, err := provideUserRepository(cfg, db)
	if err != nil {
		return nil, err
	}
	userService := service.NewUserService(userRepository)
	userController := provideUserController(userService, cfg)
	container := &Container{
		Config:         cfg,
		DB:             db,
		UserRepository: userRepository,
		UserService:    userService,
		UserController: userController,
	}
	return container, nil
}

// wire.go:

// provideDB 提供数据库连接
func provideDB(cfg *config.Config) (*gorm.DB, error) {

	if err := database.InitDatabase(&cfg.Database); err != nil {
		return nil, err
	}

	return database.GetDB(), nil
}

// provideUserRepository 根据配置提供用户仓库实现
func provideUserRepository(cfg *config.Config, db *gorm.DB) (repository.UserRepository, error) {

	switch cfg.Database.Driver {
	case "mysql":
		return mysql.NewUserRepository(), nil
	case "mongodb":
		return mongodb.NewUserRepository(), nil
	default:
		return nil, fmt.Errorf("不支持的数据库类型: %s", cfg.Database.Driver)
	}
}

// provideUserController 提供用户控制器
func provideUserController(userService *service.UserService, cfg *config.Config) *controller.UserController {
	return controller.NewUserController(userService, &cfg.JWT)
}
